---
- name: Install node and npm
  hosts: 139.59.152.17
  tasks: 
    - name: Update apt repo and cache
      apt: 
        update_cache: yes
        force_apt_get: yes
        cache_valid_time: 3600
    - name: Install a nodejs and npm
      apt: 
        pkg:
          - nodejs
          - npm

- name: Create new Linux user for a node app
  hosts: 139.59.152.17
  tasks:
    - name: Create a linux user
      user:
        name: firoz
        comment: Firoz Admin
        group: admin   
      register: user_creation_result
    - debug:
        var: user_creation_result

- name: Deploy nodejs application 
  hosts: 139.59.152.17
  become: True 
  become_user: firoz
  tasks:
    - name: Copy nodejs folder to a server
      copy:
        src: /home/fnadeer/Downloads/Nodejs-Master/simple-nodejs-master/nodejs-app-1.0.0.tgz
        dest: /home/firoz/app-1.0.0.tgz
    - name: Unarchive the tar file 
      unarchive:
        src: /home/firoz/app-1.0.0.tgz
        dest: /home/firoz
        remote_src: yes
      register: unpack_successful
    - debug:
        msg: unpack_successful
    - name: Install dependencies 
      npm:
        path: /home/firoz/package
    - name: Start the application
      command: 
        chdir: /home/firoz/package/app
        cmd: node server
      async: 1000
      poll: 0 
    - name: Ensure app is running 
      shell: ps aux | grep node
      register: app_status 
    - debug: 
        var: app_status
